---
argument_specs:
  main:
    short_description: Main entrypoint for the rootless-podman role
    description:
      - This is the main entrypoint for the rootless-podman role.
    author: Ryan Etten
    options:
      podman_user_name:
        type: str
        required: true
        description:
          - Name of the user to be enabled for Podman.
 
      podman_user_group:
        type: str
        default: "{{ podman_user_name }}"
        description:
          - Name of the primary group for the Podman user.

