---
- name: Deploy GitHub Actions Runner on RHEL with Rootless Podman
  hosts: all
  become: yes
  vars:
    runner_user: runner
    runner_home: /home/runner
    runner_version: 2.317.0
    github_org: redhatryan/podman-actions
    github_token: AYKPCAAB6HDYSG6KBJWHW3TGRRKC2
    runner_labels: self-hosted,x64,podman
  tasks:
    - name: Register the system
      command: >
        subscription-manager register --activationkey rhel-gha-podman --org 11009103
      ignore_errors: yes

    - name: Attach subscription
      command: subscription-manager attach --auto
      ignore_errors: yes

    - name: Ensure SELinux is enforcing
      command: setenforce 1

    - name: Update all packages
      yum:
        name: '*'
        state: latest

    - name: Install required packages
      yum:
        name:
          - podman
          - podman-docker
          - policycoreutils-python-utils
          - curl
          - jq
        state: present

    - name: Create runner user
      user:
        name: "{{ runner_user }}"
        shell: /bin/bash
        create_home: yes

    - name: Add runner user to sudoers
      lineinfile:
        path: /etc/sudoers.d/{{ runner_user }}
        create: yes
        line: '{{ runner_user }} ALL=(ALL) NOPASSWD:ALL'

    - name: Enable and start rootless Podman socket
      systemd:
        name: podman.socket
        state: started
        enabled: yes
        scope: user
        daemon_reload: yes

    - name: Set Docker Host environment variable
      lineinfile:
        path: /home/{{ runner_user }}/.bashrc
        line: 'export DOCKER_HOST="unix://$(podman info -f "{{.Host.RemoteSocket.Path}}")"'
        state: present

    - name: Enable lingering for runner user
      command: loginctl enable-linger {{ runner_user }}

    - name: Create GitHub Actions runner directory
      file:
        path: "{{ runner_home }}/actions-runner"
        state: directory
        owner: "{{ runner_user }}"
        group: "{{ runner_user }}"

    - name: Download GitHub Actions runner
      become: no
      become_user: "{{ runner_user }}"
      get_url:
        url: "https://github.com/actions/runner/releases/download/v{{ runner_version }}/actions-runner-linux-x64-{{ runner_version }}.tar.gz"
        dest: "{{ runner_home }}/actions-runner/actions-runner-linux-x64-{{ runner_version }}.tar.gz"

    - name: Extract GitHub Actions runner
      become: no
      become_user: "{{ runner_user }}"
      unarchive:
        src: "{{ runner_home }}/actions-runner/actions-runner-linux-x64-{{ runner_version }}.tar.gz"
        dest: "{{ runner_home }}/actions-runner"
        remote_src: yes

    - name: Configure GitHub Actions runner
      become: no
      become_user: "{{ runner_user }}"
      command: >
        {{ runner_home }}/actions-runner/config.sh --url https://github.com/{{ github_org }} --token {{ github_token }} --labels {{ runner_labels }} --unattended

    - name: Setup systemd service for runner
      copy:
        dest: "{{ runner_home }}/actions-runner/runsvc.sh"
        content: |
          [Unit]
          Description=GitHub Actions Runner
          After=network.target

          [Service]
          ExecStart={{ runner_home }}/actions-runner/bin/runsvc.sh
          User={{ runner_user }}
          WorkingDirectory={{ runner_home }}/actions-runner

          [Install]
          WantedBy=multi-user.target
      notify:
        - Start GitHub Actions Runner

  handlers:
    - name: Start GitHub Actions Runner
      systemd:
        name: runsvc.sh
        state: started
        enabled: yes
