apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ansible-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: '<your-git-repo-url>'
    targetRevision: master
    path: 'ansible'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
