---
- name: Deploy Application
 # hosts: TO_DO_LATER
  become: yes
  vars_files:
    - group_vars/main.yml
    - inventories/lab/group_vars/main.yml
  tasks:
    - name: Install dependencies
      apt:
        name:
          - curl
          - unzip
          - podman
        state: present
      when: ansible_os_family == 'Debian'
    
    - name: Install dependencies
      yum:
        name: 
          - curl
          - podman
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Enable and start Podman socket for the user
      systemd:
        name: podman.socket
        state: started
        enabled: yes
        user: true

    - name: Download FetchIt binary
      get_url:
        url: "https://github.com/containers/fetchit/releases/download/v0.0.1/fetchit"
        dest: /usr/local/bin/fetchit
        mode: '0755'

    - name: Create FetchIt configuration directory
      file:
        path: /etc/fetchit
        state: directory
        mode: '0755'

    - name: Copy FetchIt configuration file
      copy:
        src: /gitops/fetch-it/config.yaml
        dest: /etc/fetchit/config.yaml
        mode: '0644'

    - name: Create systemd service file for FetchIt
      copy:
        dest: /etc/systemd/system/fetchit.service
        content: |
          [Unit]
          Description=FetchIt Service
          After=network.target

          [Service]
          ExecStart=/usr/local/bin/fetchit -c /etc/fetchit/config.yaml
          Restart=always
          User=root

          [Install]
          WantedBy=multi-user.target
      notify: restart fetchit

    - name: Enable FetchIt service
      systemd:
        name: fetchit
        enabled: yes
        state: started

  handlers:
    - name: restart fetchit
      systemd:
        name: fetchit
        state: restarted
